name: Deploy static site

on:
  push:
    branches: main

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy to Github
        uses: actions/deploy-pages@v4